
export const CREATE_SIGNAL_HISTORY  = "CREATE_SIGNAL_HISTORY ";
export const UPDATE_SIGNAL_HISTORY  = "UPDATE_SIGNAL_HISTORY ";
export const DELETE_SIGNAL_HISTORY  = "DELETE_SIGNAL_HISTORY ";
export const FETCH_SIGNAL_HISTORY = "FETCH_SIGNAL_HISTORY";